<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Hello_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


# ***Importing Libraries***

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# ***Import Dataset***

In [6]:
pwd

'/content'

In [7]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab


In [36]:
dataset = pd.read_csv('Data.csv', encoding='cp1252')
X = dataset.iloc[:, 2:13].values
Y = dataset.iloc[: , 13].values

In [37]:
dataset.head()

Song_ID                     Song_Title  ... Unnamed: 19  Unnamed: 20
0        1                          Diana  ...         NaN          NaN
1        2  Don't forget where you belong  ...         NaN          NaN
2        3                        Strong   ...         NaN          NaN
3        4                        Happily  ...         NaN          NaN
4        5              Better than words  ...         NaN          NaN

[5 rows x 21 columns]

In [38]:
X

array([['Pop', 0.06, 172, ..., 1, 4, 2],
       ['Pop', 0.1, 92, ..., 1, 4, 7],
       ['Pop', 0.06, 115, ..., 1, 4, 0],
       ...,
       ['Pop', 0.01, 123, ..., 1, 4, 4],
       ['Pop', 0.56, 184, ..., 0, 4, 10],
       ['Pop', 0.21, 110, ..., 0, 4, 1]], dtype=object)

In [30]:
print(X.shape)

(800, 11)


In [39]:
Y

array(['Happy', 'Sad', 'Dark', 'Scary', 'Tense', 'Love', 'Inspiration',
       'Motivation', 'Angry', 'Calm', 'Love', 'Dreamy', 'Happy', 'Sad',
       'Dark', 'Scary', 'Tense', 'Love', 'Inspiration', 'Motivation',
       'Angry', 'Calm', 'Sad', 'Happy', 'Sad', 'Dark', 'Scary', 'Tense',
       'Happy', 'Sad', 'Dark', 'Scary', 'Tense', 'Happy', 'Sad', 'Dark',
       'Scary', 'Tense', 'Love', 'Inspiration', 'Motivation', 'Angry',
       'Calm', 'Love', 'Dreamy', 'Happy', 'Sad', 'Dark', 'Scary', 'Tense',
       'Love', 'Inspiration', 'Motivation', 'Angry', 'Calm', 'Love',
       'Dreamy', 'Love', 'Angry', 'Calm', 'Calm', 'Angry', 'Calm',
       'Angry', 'Happy', 'Happy', 'Sad', 'Inspiration', 'Inspiration ',
       'Sad', 'Sad', 'Sad', 'Sad', 'Inspiration', 'Sad', 'Angry', 'Angry',
       'Angry', 'Calm', 'Dreamy', 'Happy', 'Tense', 'Sad', 'Sad', 'Happy',
       'Inspiration', 'Happy', 'Motivation', 'Inspiration', 'Love',
       'Tense', 'Happy', 'Sad', 'Dark', 'Love', 'Calm', 'Happy',
   

In [32]:
print(Y.shape)

(800,)


# ***Encord Categorical Data***

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)


In [34]:
print(y)

[ 6 13  3 15 16 10  8 12  0  1 10  4  6 13  3 15 16 10  8 12  0  1 13  6
 13  3 15 16  6 13  3 15 16  6 13  3 15 16 10  8 12  0  1 10  4  6 13  3
 15 16 10  8 12  0  1 10  4 10  0  1  1  0  1  0  6  6 13  8  9 13 13 13
 13  8 13  0  0  0  1  4  6 16 13 13  6  8  6 12  8 10 16  6 13  3 10  1
  6 12 15 10 15  6  6 10 12 10 13  6  6  4  1 16  0  4  6 13  6  6  6  6
  6  6  6  8  6  6  6 16  6  6  6  3  6  6  6  6 13  3 15 16 10  8 12  0
  1 10  4  6 13 13 11 13  6 10  0  0  0  0  0  1  4  0  0  0  0  0  0  0
 12  1  8 13 13  0  1  4 13 13 16  0  1 12 13  9  9 13 13 13 10  8  8 12
  8  8  8  8  8  8  8  8  8  6  6  3 10 10  7  3 13  6  6  1  6  6 10  4
 13 10 16  0  3 16 15 16 15  3 16 15  3  3 16 15 15 12  7  7  7 12 16 13
 13 13 13 13 13 13 14 13 13  1  1  1  1  1  1  1  1 10  1  6  1  4  1  1
  1  1  1  1 13  1 12 13  1 12 16  1  6  6  1  1 13  1 13 13 13 13 13 13
 13 13 13 13 13 13 13 13 13 13  3 13 13 13 13  6 13 13 13  6 13  3  6 14
  1 12 14 13 13  4 12  6  6  6  4 10 10 10 10 10 10

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 4 2]
 [1.0 0.0 0.0 ... 1 4 7]
 [1.0 0.0 0.0 ... 1 4 0]
 ...
 [1.0 0.0 0.0 ... 1 4 4]
 [1.0 0.0 0.0 ... 0 4 10]
 [1.0 0.0 0.0 ... 0 4 1]]


# ***Spliting the data to testing and trainng***

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [45]:
print(X_train)
print(X_train.shape)

[[1.0 0.0 0.0 ... 1 4 4]
 [1.0 0.0 0.0 ... 0 3 2]
 [1.0 0.0 0.0 ... 1 4 2]
 ...
 [1.0 0.0 0.0 ... 1 4 4]
 [1.0 0.0 0.0 ... 1 4 0]
 [1.0 0.0 0.0 ... 0 4 6]]
(640, 25)


In [46]:
print(X_test)
print(X_test.shape)

[[1.0 0.0 0.0 ... 1 4 2]
 [1.0 0.0 0.0 ... 0 4 6]
 [1.0 0.0 0.0 ... 1 4 2]
 ...
 [1.0 0.0 0.0 ... 0 4 5]
 [1.0 0.0 0.0 ... 1 5 0]
 [1.0 0.0 0.0 ... 0 4 6]]
(160, 25)


In [47]:
print(y_train)
print(y_train.shape)

[ 6 16  6 12 14 13 16  0 13  1 14  6 13 12  6  9  1  9  0 14  6  6 10 13
  6 16  6 14 13  6  6  6  6 13  6  4 13  3  8  6  6 12 10  1 13 13  1 12
 10 13 15  9  0  1  6 13 16  6  3  6  1  8  3  6 10 13  6  6 16 13  4  3
 13  3  1  6 13 13  9  9  8  6 10  6 13 13  3 10  4  0  1  6  3  6  6  6
 13  9 10  4 10 10  6  1  3  7  7  0 16 16 15  6  3 13 13 13  6 13  1 10
 13 14  6 16  1  1 13 14  9  6  1 10  6 13  1 13  8  1  4  6 16  6  6  1
  0  1  6 17  6  1  6 13  4  0 16 14 13 13 10  8  7  9  4  4  6 13 17 10
  6  6 10  0  8  6  8 16  6  6  7  0 13  3 10 14  9  7 14  6  6  1  9 17
  0  8 17  1  6 13 10  6 13  1  1 10 10 14 13  8 16  6  1  1 10 16  1  6
 16 13  4  1  4  6  6  8  3  6 13  9  3  9 16  0 14  1 15 13 13 13  9  6
 12  0  1 13 15 12  1  6 13 13  0  1  9 13 12  1  0 10 12  6  8  4  1  9
 12  3  6  1  0 12 15  3  4  3  6 13  6  3  4 13 10  6 13  6 13  3  8 12
  3 13 13  3  1 15  6  9 10 13  3  9  9 13  3  6  1 12 13 13  1  4 13 13
  0  4  0 15 10 13  6 13 10 13 16 14 13  0 17 14 15

In [48]:
print(y_test)
print(y_test.shape)

[ 0  6  4 13 13 16  6  1  6 10  1 16 13  8  6 13  4 14 15 13 13 16  0  6
  6  3 16  1  3  6 10 16 12 14 16  8 10  2  3  3 10  4  3  6 13 14  7  6
 13  3 13  6  6  9 12  6 13  8 10  8 13 13  6  6 12  1 13  6 15  6 13  6
 14  6 15  6  7  1 13 15 13 16 13 13 13  6 13  8  4 15 10  3  6  4  6  1
 13 13 12  4 16 17  6  5  0 13  6 17 16  6  3  0 10 13  3  6  0  1  6 16
 16  6 10 13  1 14  0 16 13  0 13 16  6  3  1  6  6  6 12 13 10 15  6  6
  4 13  6  6  3 13  3 17 16  4  0  6  3  6 14  6]
(160,)
