<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Hello_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


# ***Importing Libraries***

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# ***Import Dataset***

In [13]:
pwd

'/content/drive/My Drive/4th Year Research/M3/Test Implementation/Test-Google-Colab'

In [14]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab


In [91]:
dataset = pd.read_csv('Data.csv', encoding='cp1252')
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[: , 12].values
Y1 = dataset.iloc[: , 13].values
Y2 = dataset.iloc[: , 14].values
Y3 = dataset.iloc[: , 15].values

In [92]:
dataset.head()

Genre  Acorsticness  Tempo (bpm)  ...  Unnamed: 17  Unnamed: 18  Unnamed: 19
0   Pop          0.06          172  ...          NaN          NaN          NaN
1   Pop          0.10           92  ...          NaN          NaN          NaN
2   Pop          0.06          115  ...          NaN          NaN          NaN
3   Pop          0.04          117  ...          NaN          NaN          NaN
4   Pop          0.11          158  ...          NaN          NaN          NaN

[5 rows x 20 columns]

In [93]:
X

array([['Pop', 0.06, 172, ..., 1, 4, 2],
       ['Pop', 0.1, 92, ..., 1, 4, 7],
       ['Pop', 0.06, 115, ..., 1, 4, 0],
       ...,
       ['Pop', 0.01, 123, ..., 1, 4, 4],
       ['Pop', 0.56, 184, ..., 0, 4, 10],
       ['Pop', 0.21, 110, ..., 0, 4, 1]], dtype=object)

In [94]:
print(X.shape)

(800, 11)


In [95]:
Y

array(['Inspiration', 'Inspiration', 'Happy', 'Happy', 'Inspiration',
       'Inspiration', 'Sad', 'Dreamy', 'Happy', 'Happy', 'Love',
       'Inspiration', 'Inspiration', 'Inspiration', 'Inspiration',
       'Happy', 'Calm', 'Inspiration', 'Dreamy', 'Love', 'Happy', 'Love',
       'Sad', 'Sad', 'Love', 'Calm', 'Love', 'Happy', 'Happy', 'Tense',
       'Dreamy', 'Tense', 'Dreamy', 'Happy', 'Happy', 'Sad',
       'Inspiration', 'Happy', 'Angry', 'Inspiration', 'Tense', 'Happy',
       'Happy', 'Happy', 'Inspiration', 'Inspiration', 'Tense', 'Love',
       'Inspiration', 'Love', 'Happy', 'Love', 'Tense', 'Dreamy', 'Calm',
       'Happy', 'Angry', 'Calm', 'Angry', 'Calm', 'Angry', 'Inspiration',
       'Tense', 'Tense', 'Dreamy', 'Angry', 'Angry', 'Inspiration',
       'Inspiration ', 'Angry', 'Tense', 'Angry', 'Tense', 'Inspiration',
       'Happy', 'Tense', 'Scary', 'Tense', 'Dreamy', 'Inspiration',
       'Happy', 'Love', 'Sad', 'Inspiration', 'Happy', 'Inspiration',
       'Happy', 'I

In [96]:
print(Y.shape)

(800,)


In [97]:
print(X.shape)

(800, 11)


In [98]:
Y1

array(['Inspiration', 'Inspiration', 'Happy', 'Happy', 'Inspiration',
       'Inspiration', 'Sad', 'Dreamy', 'Happy', 'Happy', 'Love',
       'Inspiration', 'Inspiration', 'Inspiration', 'Inspiration',
       'Happy', 'Calm', 'Inspiration', 'Dreamy', 'Love', 'Happy', 'Love',
       'Sad', 'Sad', 'Love', 'Calm', 'Love', 'Happy', 'Happy', 'Tense',
       'Dreamy', 'Tense', 'Dreamy', 'Happy', 'Happy', 'Sad',
       'Inspiration', 'Happy', 'Angry', 'Inspiration', 'Tense', 'Happy',
       'Happy', 'Happy', 'Inspiration', 'Inspiration', 'Tense', 'Love',
       'Inspiration', 'Love', 'Happy', 'Love', 'Tense', 'Dreamy', 'Calm',
       'Happy', 'Angry', 'Calm', 'Angry', 'Calm', 'Angry', 'Inspiration',
       'Tense', 'Tense', 'Dreamy', 'Angry', 'Angry', 'Inspiration',
       'Inspiration ', 'Angry', 'Tense', 'Angry', 'Tense', 'Inspiration',
       'Happy', 'Tense', 'Scary', 'Tense', 'Dreamy', 'Inspiration',
       'Happy', 'Love', 'Sad', 'Inspiration', 'Happy', 'Inspiration',
       'Happy', 'I

In [99]:
Y2

array(['Inspiration', 'Inspiration', 'Happy', 'Happy', 'Inspiration',
       'Inspiration', 'Sad', 'Dreamy', 'Happy', 'Happy', 'Love',
       'Inspiration', 'Inspiration', 'Inspiration', 'Inspiration',
       'Happy', 'Calm', 'Inspiration', 'Dreamy', 'Love', 'Happy', 'Love',
       'Sad', 'Sad', 'Love', 'Calm', 'Love', 'Happy', 'Happy', 'Tense',
       'Dreamy', 'Tense', 'Dreamy', 'Happy', 'Happy', 'Sad',
       'Inspiration', 'Happy', 'Angry', 'Inspiration', 'Tense', 'Happy',
       'Happy', 'Happy', 'Inspiration', 'Inspiration', 'Tense', 'Love',
       'Inspiration', 'Love', 'Happy', 'Love', 'Tense', 'Dreamy', 'Calm',
       'Happy', 'Angry', 'Calm', 'Angry', 'Calm', 'Angry', 'Inspiration',
       'Tense', 'Tense', 'Dreamy', 'Angry', 'Angry', 'Inspiration',
       'Inspiration ', 'Angry', 'Tense', 'Angry', 'Tense', 'Inspiration',
       'Happy', 'Tense', 'Scary', 'Tense', 'Dreamy', 'Inspiration',
       'Happy', 'Love', 'Sad', 'Inspiration', 'Happy', 'Inspiration',
       'Happy', 'I

In [100]:
Y3

array([ 6,  6,  1,  1,  6,  6,  2,  4,  1,  1,  9,  6,  6,  6,  6,  1,  3,
        6,  4,  9,  1,  9,  2,  2,  9,  3,  9,  1,  1,  7,  4,  7,  4,  1,
        1,  2,  6,  1,  5,  6,  7,  1,  1,  1,  6,  6,  7,  9,  6,  9,  1,
        9,  7,  4,  3,  1,  5,  3,  5,  3,  5,  6,  7,  7,  4,  5,  5,  6,
        6,  5,  7,  5,  7,  6,  1,  7,  8,  7,  4,  6,  1,  9,  2,  6,  1,
        6,  1,  6,  6,  9,  9,  2,  6,  5,  4,  3,  1,  1,  7,  9,  6,  2,
        1,  9,  9,  7,  9,  1,  1,  4,  4,  3,  1,  4,  4,  1,  1,  1,  1,
        1,  1,  1,  1,  6,  1,  1,  1,  7,  1,  1,  1,  1,  1,  1,  9,  7,
        6,  4,  3,  9,  4,  4,  4,  4,  7,  2,  6,  4,  1,  2,  9,  1,  1,
        1,  5,  5,  5,  5,  5,  7,  7,  5,  5,  5,  5,  5,  5,  5,  6,  3,
        6,  2,  2,  5,  3,  4,  2,  2,  4,  4,  3,  6,  2,  6,  6,  2,  2,
        2,  9,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  1,  1, 10,
        1,  9,  1, 10,  9,  7,  1,  3,  4,  1,  9,  1,  4,  9,  5,  6,  7,
        8,  8,  6, 10,  6

# ***Encord Categorical Data***

In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
y1 = le.fit_transform(Y1)
y2 = le.fit_transform(Y2)


In [106]:
print(y)

[ 9  9  7  7  9  9 15  5  7  7 12  9  9  9  9  7  2  9  5 12  7 12 15 15
 12  2 12  7  7 19  5 19  5  7  7 15  9  7  0  9 19  7  7  7  9  9 19 12
  9 12  7 12 19  5  2  7  0  2  0  2  0  9 19 19  5  0  0  9 10  0 19  0
 19  9  7 19 18 19  5  9  7 12 15  9  7  9  7  9  9 12 12 15  9  0  5  2
  7  7 19 12  9 15  7 12 12 19 12  7  7  5  5  2  7  5  5  7  7  7  7  7
  7  7  7  9  7  7  7 19  7  7  7  8  7  7 12 19  9  3  3 12  6  5  5  5
 19 15  9  8  7 15 13  7  7  7  0  0  0  0  0 19 19  0  0  0  0  0  0  0
  9  2  9 15 15  0  2  5 15 15  5  8  2  9 15 10 10 15 15 15 12  9  9  9
  9  9  9  9  9  9  9  9  9  7  7  4  7 12  8  4 12 19  7  2 13 13 12  7
  7 12  0  9 19  0  1  9 19  9 19 20  5  5 18 19 18  9  8  8  5  9 19 15
 15 15 15 15 15 15 16 15 15  2  2  2  2  2  2  2  2 12  2  6  2  2  2  2
  2  2  2  2 15  2  9 15  2  7 19  2  5 13 15 15 15 15 15 15 13 15 15 15
 13 15 15 15 15 15 15 15 15 15  5 13 15 15  5  9  5 19 15  7  9 19 13 16
  2 11 16 12 13  5  9  7  7  7  5 12 12 12 12 12 12

In [107]:
y1

array([ 9,  9,  7,  7,  9,  9, 14,  5,  7,  7, 12,  9,  9,  9,  9,  7,  1,
        9,  5, 12,  7, 12, 14, 14, 12,  1, 12,  7,  7, 18,  5, 18,  5,  7,
        7, 14,  9,  7,  0,  9, 18,  7,  7,  7,  9,  9, 18, 12,  9, 12,  7,
       12, 18,  5,  1,  7,  0,  1,  0,  1,  0,  9, 18, 18,  5,  0,  0,  9,
       10,  0, 18,  0, 18,  9,  7, 18, 17, 18,  5,  9,  7, 12, 14,  9,  7,
        9,  7,  9,  9, 12, 12, 14,  9,  0,  5,  1,  7,  7, 18, 12,  9, 14,
        7, 12, 12, 18, 12,  7,  7,  5,  5,  1,  7,  5,  5,  7,  7,  7,  7,
        7,  7,  7,  7,  9,  7,  7,  7, 18,  7,  7,  7,  1,  7,  7, 12, 18,
        9,  5,  5, 12, 14,  5,  1,  5, 18, 14,  9,  5,  7, 14, 13,  7,  7,
        7,  0,  0,  0,  0,  0, 18, 18,  0,  0,  0,  0,  0,  0,  0,  9,  1,
        9, 14, 14,  0,  1,  5, 14, 14,  5,  5,  1,  9, 14,  9,  9, 14, 14,
       14, 12,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  7,  7,  3,
        7, 12,  8,  3, 12, 18,  7,  1,  5,  7, 12,  7, 12, 12,  0,  9, 18,
       17, 17,  9,  3,  9

In [108]:
y2

array([ 9,  9,  7,  7,  9,  9, 14,  5,  7,  7, 12,  9,  9,  9,  9,  7,  1,
        9,  5, 12,  7, 12, 14, 14, 12,  1, 12,  7,  7, 18,  5, 18,  5,  7,
        7, 14,  9,  7,  0,  9, 18,  7,  7,  7,  9,  9, 18, 12,  9, 12,  7,
       12, 18,  5,  1,  7,  0,  1,  0,  1,  0,  9, 18, 18,  5,  0,  0,  9,
       10,  0, 18,  0, 18,  9,  7, 18, 17, 18,  5,  9,  7, 12, 14,  9,  7,
        9,  7,  9,  9, 12, 12, 14,  9,  0,  5,  1,  7,  7, 18, 12,  9, 14,
        7, 12, 12, 18, 12,  7,  7,  5,  5,  1,  7,  5,  5,  7,  7,  7,  7,
        7,  7,  7,  7,  9,  7,  7,  7, 18,  7,  7,  7,  1,  7,  7, 12, 18,
        9,  5,  5, 12, 14,  5,  5,  5, 18, 14,  9,  5,  7, 14, 13,  7,  7,
        7,  0,  0,  0,  0,  0, 18, 18,  0,  0,  0,  0,  0,  0,  0,  9,  1,
        9, 14, 14,  0,  1,  5, 14, 14,  5,  5,  1,  9, 14,  9,  9, 14, 14,
       14, 12,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  7,  7,  3,
        7, 12,  8,  3, 12, 18,  7,  1,  5,  7, 12,  7,  5, 12,  0,  9, 18,
       17, 17,  9,  3,  9

In [109]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 4 2]
 [1.0 0.0 0.0 ... 1 4 7]
 [1.0 0.0 0.0 ... 1 4 0]
 ...
 [1.0 0.0 0.0 ... 1 4 4]
 [1.0 0.0 0.0 ... 0 4 10]
 [1.0 0.0 0.0 ... 0 4 1]]


# ***Spliting the data to testing and trainng***

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [111]:
print(X_train)
print(X_train.shape)

[[1.0 0.0 0.0 ... 1 3 6]
 [1.0 0.0 0.0 ... 0 4 9]
 [1.0 0.0 0.0 ... 1 3 9]
 ...
 [1.0 0.0 0.0 ... 1 4 8]
 [1.0 0.0 0.0 ... 0 3 7]
 [1.0 0.0 0.0 ... 0 4 5]]
(640, 25)


In [112]:
print(X_test)
print(X_test.shape)

[[1.0 0.0 1.0 ... 1 3 5]
 [1.0 0.0 0.0 ... 1 4 2]
 [1.0 0.0 0.0 ... 1 4 0]
 ...
 [1.0 0.0 0.0 ... 1 4 8]
 [0.0 1.0 0.0 ... 0 3 9]
 [1.0 0.0 0.0 ... 0 4 4]]
(160, 25)


In [113]:
print(y_train)
print(y_train.shape)

[15 18  5 19 19  9 15 15 20  2  7  7 15  7  7  9  0 16  7  7 20  9  5  7
  5 15  2  4 18  7  2  9 19  7 10 18 15  7  9 13  7 15 20 15  2 10  4  9
 10  9 15 12 16  9  2  2 19  5 15 15  5  6  9  5  7 19  9  4 15 19 12 15
 15 12  5  7 15 12 19 15 19  7  7 15  5  4  2 15  7 19  9  2  2  2  4  5
 15 12  2  7  0 19 12  7 15  7  9  0 15 15  5  5  0  5  5 15  0  5 15  7
  7  7  4  9  7  5 16  7 19 15  4  7  7 15  9 15  5 19 12 20 12  2 12  5
  7 15  0 16 18 12 18  9  5 10  9  5  7  9  0  5 11 12  4  5  8 10  7  4
 19  2 12 19  8  9 19 15  8 15  7  7 15  9  2 12  9  7  7  7 13 20  5 15
 16  2  8  7 20 16 20  7 19 12  5  7 19  7  7 12 12  7  2 15  4 15  7  7
  7  8  2  9  5 12 19 15 12 15 15  7 19 19  8  9  7 15 10  7 12  7  7  0
  5  7  6  7  7 15  7  7  5  7  3 19  5 19  4 19 19  2 16  6  7 15  7 19
  4  7  2  5  5  7  9  2  7  2  9 15  0  7  0 20  2  7  2  4 10 12  5  7
  7  0  0 15  7 18 15  5  5  2  4  0  7  0  7  2  5  5  4  7  7  7  2  5
 16 15 15 15  0 12 12  4 16  9  7 15  9  7  9  7 15

In [114]:
print(y_test)
print(y_test.shape)

[13 20  9 19 15 15  5 10  7 19  9 15 18  7  7  7 19  1  0  7  7  5  5 15
 18 15  0 15  5  5 15 16  9 20  2 19 15 10  5  2 12  7  2 10 15  2  7 15
 12  6  8 16  2 19  2  7 15 15  4  5 12  7 12 10 15 18 15  5  2  8 20  2
  9 12 20  9 15  8  2  7  2  2  7  7  7 15  5  4  7 15  4  7 12 20 15  2
 16  7  4  2 20 15  7 10  5  7  7 20 15  7  7  7  7 18 15 16 15  9  9  7
 12  5 12 16 10 20 15  7 15 19  7  2  7 14  5 13  9  7  4  4 20  2 12  7
  2  7  2  0 12  4  5  7  7  2  9  9  7 13  2 15]
(160,)


# ***ANN***

In [115]:
import tensorflow as tf

In [116]:
tf.__version__

'2.7.0'

**Feature Scaling**

In [117]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# ***Build ANN***

In [118]:
ann = tf.keras.models.Sequential()

In [119]:
ann.add(tf.keras.layers.Dense(units=24, activation='relu'))

In [120]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [121]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [123]:
ann.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
64/64 [==============================] - 0s 1ms/step - loss: -426774.4062 - accuracy: 0.0000e+00
Epoch 2/100
64/64 [==============================] - 0s 1ms/step - loss: -428372.1875 - accuracy: 0.0000e+00
Epoch 3/100
64/64 [==============================] - 0s 2ms/step - loss: -429979.5938 - accuracy: 0.0000e+00
Epoch 4/100
64/64 [==============================] - 0s 2ms/step - loss: -431589.6562 - accuracy: 0.0000e+00
Epoch 5/100
64/64 [==============================] - 0s 2ms/step - loss: -433189.9375 - accuracy: 0.0000e+00
Epoch 6/100
64/64 [==============================] - 0s 2ms/step - loss: -434810.5625 - accuracy: 0.0000e+00
Epoch 7/100
64/64 [==============================] - 0s 2ms/step - loss: -436423.0625 - accuracy: 0.0000e+00
Epoch 8/100
64/64 [==============================] - 0s 2ms/step - loss: -438043.0938 - accuracy: 0.0000e+00
Epoch 9/100
64/64 [==============================] - 0s 2ms/step - loss: -439664.8438 - accuracy: 0.0000e+00
Epoch 10/100
64/64 

# ***Naive Bayes***

In [124]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [125]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[13 13]
 [ 4 20]
 [13  9]
 [ 6 19]
 [12 15]
 [ 4 15]
 [ 3  5]
 [10 10]
 [10  7]
 [ 4 19]
 [13  9]
 [ 3 15]
 [ 8 18]
 [13  7]
 [ 8  7]
 [ 8  7]
 [10 19]
 [ 4  1]
 [ 6  0]
 [10  7]
 [ 8  7]
 [13  5]
 [ 4  5]
 [ 8 15]
 [ 4 18]
 [ 6 15]
 [ 8  0]
 [ 3 15]
 [13  5]
 [ 3  5]
 [ 6 15]
 [16 16]
 [13  9]
 [20 20]
 [18  2]
 [ 6 19]
 [15 15]
 [ 8 10]
 [ 3  5]
 [ 0  2]
 [ 6 12]
 [13  7]
 [ 8  2]
 [ 4 10]
 [ 4 15]
 [ 8  2]
 [10  7]
 [16 15]
 [ 8 12]
 [16  6]
 [ 8  8]
 [16 16]
 [18  2]
 [13 19]
 [ 8  2]
 [12  7]
 [15 15]
 [ 3 15]
 [ 8  4]
 [ 6  5]
 [ 8 12]
 [13  7]
 [12 12]
 [10 10]
 [ 6 15]
 [ 4 18]
 [ 6 15]
 [13  5]
 [18  2]
 [12  8]
 [19 20]
 [ 4  2]
 [ 3  9]
 [ 8 12]
 [ 4 20]
 [ 6  9]
 [13 15]
 [ 8  8]
 [ 8  2]
 [13  7]
 [18  2]
 [18  2]
 [13  7]
 [ 8  7]
 [ 8  7]
 [16 15]
 [ 6  5]
 [ 8  4]
 [ 8  7]
 [10 15]
 [ 4  4]
 [10  7]
 [ 8 12]
 [20 20]
 [13 15]
 [ 6  2]
 [ 4 16]
 [ 8  7]
 [ 4  4]
 [18  2]
 [20 20]
 [ 3 15]
 [ 8  7]
 [ 8 10]
 [ 8  5]
 [ 8  7]
 [13  7]
 [18 20]
 [19 15]
 [ 6  7]
 [ 8  7]
 

In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  1  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  2  0  1  0  1  0  6  0  0  1  0  0  0  0  7  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  1  0  2  0  2  0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  1  0 16  0  5  3  9  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  2  1  0  1  0  1  0  0  0  4  0  0  0  0  0  1]
 [ 0  0  0  0  1  0  0  0  3  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  1  0  4  0  0  1  1  0  0  1  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  5  2  0  7  0  1  0  2  1  2  0  2  2  0  1  0]
 [ 0  0  0  0  1  0  1  0  0  0  0  0  1  0  0  2  0  0  0]
 [ 0  0  0  0  3  0  0  0  1  0  0  0  0

0.13125