<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Hello_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


# ***Importing Libraries***

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# ***Import Dataset***

In [13]:
pwd

'/content/drive/My Drive/4th Year Research/M3/Test Implementation/Test-Google-Colab'

In [14]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab


In [91]:
dataset = pd.read_csv('Data.csv', encoding='cp1252')
X = dataset.iloc[:, 0:11].values
Y = dataset.iloc[: , 12].values
Y1 = dataset.iloc[: , 13].values
Y2 = dataset.iloc[: , 14].values
Y3 = dataset.iloc[: , 15].values

In [92]:
dataset.head()

Genre  Acorsticness  Tempo (bpm)  ...  Unnamed: 17  Unnamed: 18  Unnamed: 19
0   Pop          0.06          172  ...          NaN          NaN          NaN
1   Pop          0.10           92  ...          NaN          NaN          NaN
2   Pop          0.06          115  ...          NaN          NaN          NaN
3   Pop          0.04          117  ...          NaN          NaN          NaN
4   Pop          0.11          158  ...          NaN          NaN          NaN

[5 rows x 20 columns]

In [93]:
X

array([['Pop', 0.06, 172, ..., 1, 4, 2],
       ['Pop', 0.1, 92, ..., 1, 4, 7],
       ['Pop', 0.06, 115, ..., 1, 4, 0],
       ...,
       ['Pop', 0.01, 123, ..., 1, 4, 4],
       ['Pop', 0.56, 184, ..., 0, 4, 10],
       ['Pop', 0.21, 110, ..., 0, 4, 1]], dtype=object)

In [94]:
print(X.shape)

(800, 11)


In [95]:
Y

array(['Inspiration', 'Inspiration', 'Happy', 'Happy', 'Inspiration',
       'Inspiration', 'Sad', 'Dreamy', 'Happy', 'Happy', 'Love',
       'Inspiration', 'Inspiration', 'Inspiration', 'Inspiration',
       'Happy', 'Calm', 'Inspiration', 'Dreamy', 'Love', 'Happy', 'Love',
       'Sad', 'Sad', 'Love', 'Calm', 'Love', 'Happy', 'Happy', 'Tense',
       'Dreamy', 'Tense', 'Dreamy', 'Happy', 'Happy', 'Sad',
       'Inspiration', 'Happy', 'Angry', 'Inspiration', 'Tense', 'Happy',
       'Happy', 'Happy', 'Inspiration', 'Inspiration', 'Tense', 'Love',
       'Inspiration', 'Love', 'Happy', 'Love', 'Tense', 'Dreamy', 'Calm',
       'Happy', 'Angry', 'Calm', 'Angry', 'Calm', 'Angry', 'Inspiration',
       'Tense', 'Tense', 'Dreamy', 'Angry', 'Angry', 'Inspiration',
       'Inspiration ', 'Angry', 'Tense', 'Angry', 'Tense', 'Inspiration',
       'Happy', 'Tense', 'Scary', 'Tense', 'Dreamy', 'Inspiration',
       'Happy', 'Love', 'Sad', 'Inspiration', 'Happy', 'Inspiration',
       'Happy', 'I

In [96]:
print(Y.shape)

(800,)


In [97]:
print(X.shape)

(800, 11)


In [98]:
Y1

array(['Inspiration', 'Inspiration', 'Happy', 'Happy', 'Inspiration',
       'Inspiration', 'Sad', 'Dreamy', 'Happy', 'Happy', 'Love',
       'Inspiration', 'Inspiration', 'Inspiration', 'Inspiration',
       'Happy', 'Calm', 'Inspiration', 'Dreamy', 'Love', 'Happy', 'Love',
       'Sad', 'Sad', 'Love', 'Calm', 'Love', 'Happy', 'Happy', 'Tense',
       'Dreamy', 'Tense', 'Dreamy', 'Happy', 'Happy', 'Sad',
       'Inspiration', 'Happy', 'Angry', 'Inspiration', 'Tense', 'Happy',
       'Happy', 'Happy', 'Inspiration', 'Inspiration', 'Tense', 'Love',
       'Inspiration', 'Love', 'Happy', 'Love', 'Tense', 'Dreamy', 'Calm',
       'Happy', 'Angry', 'Calm', 'Angry', 'Calm', 'Angry', 'Inspiration',
       'Tense', 'Tense', 'Dreamy', 'Angry', 'Angry', 'Inspiration',
       'Inspiration ', 'Angry', 'Tense', 'Angry', 'Tense', 'Inspiration',
       'Happy', 'Tense', 'Scary', 'Tense', 'Dreamy', 'Inspiration',
       'Happy', 'Love', 'Sad', 'Inspiration', 'Happy', 'Inspiration',
       'Happy', 'I

In [99]:
Y2

array(['Inspiration', 'Inspiration', 'Happy', 'Happy', 'Inspiration',
       'Inspiration', 'Sad', 'Dreamy', 'Happy', 'Happy', 'Love',
       'Inspiration', 'Inspiration', 'Inspiration', 'Inspiration',
       'Happy', 'Calm', 'Inspiration', 'Dreamy', 'Love', 'Happy', 'Love',
       'Sad', 'Sad', 'Love', 'Calm', 'Love', 'Happy', 'Happy', 'Tense',
       'Dreamy', 'Tense', 'Dreamy', 'Happy', 'Happy', 'Sad',
       'Inspiration', 'Happy', 'Angry', 'Inspiration', 'Tense', 'Happy',
       'Happy', 'Happy', 'Inspiration', 'Inspiration', 'Tense', 'Love',
       'Inspiration', 'Love', 'Happy', 'Love', 'Tense', 'Dreamy', 'Calm',
       'Happy', 'Angry', 'Calm', 'Angry', 'Calm', 'Angry', 'Inspiration',
       'Tense', 'Tense', 'Dreamy', 'Angry', 'Angry', 'Inspiration',
       'Inspiration ', 'Angry', 'Tense', 'Angry', 'Tense', 'Inspiration',
       'Happy', 'Tense', 'Scary', 'Tense', 'Dreamy', 'Inspiration',
       'Happy', 'Love', 'Sad', 'Inspiration', 'Happy', 'Inspiration',
       'Happy', 'I

In [100]:
Y3

array([ 6,  6,  1,  1,  6,  6,  2,  4,  1,  1,  9,  6,  6,  6,  6,  1,  3,
        6,  4,  9,  1,  9,  2,  2,  9,  3,  9,  1,  1,  7,  4,  7,  4,  1,
        1,  2,  6,  1,  5,  6,  7,  1,  1,  1,  6,  6,  7,  9,  6,  9,  1,
        9,  7,  4,  3,  1,  5,  3,  5,  3,  5,  6,  7,  7,  4,  5,  5,  6,
        6,  5,  7,  5,  7,  6,  1,  7,  8,  7,  4,  6,  1,  9,  2,  6,  1,
        6,  1,  6,  6,  9,  9,  2,  6,  5,  4,  3,  1,  1,  7,  9,  6,  2,
        1,  9,  9,  7,  9,  1,  1,  4,  4,  3,  1,  4,  4,  1,  1,  1,  1,
        1,  1,  1,  1,  6,  1,  1,  1,  7,  1,  1,  1,  1,  1,  1,  9,  7,
        6,  4,  3,  9,  4,  4,  4,  4,  7,  2,  6,  4,  1,  2,  9,  1,  1,
        1,  5,  5,  5,  5,  5,  7,  7,  5,  5,  5,  5,  5,  5,  5,  6,  3,
        6,  2,  2,  5,  3,  4,  2,  2,  4,  4,  3,  6,  2,  6,  6,  2,  2,
        2,  9,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  1,  1, 10,
        1,  9,  1, 10,  9,  7,  1,  3,  4,  1,  9,  1,  4,  9,  5,  6,  7,
        8,  8,  6, 10,  6

# ***Encord Categorical Data***

In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
y1 = le.fit_transform(Y1)
y2 = le.fit_transform(Y2)


In [106]:
print(y)

[ 9  9  7  7  9  9 15  5  7  7 12  9  9  9  9  7  2  9  5 12  7 12 15 15
 12  2 12  7  7 19  5 19  5  7  7 15  9  7  0  9 19  7  7  7  9  9 19 12
  9 12  7 12 19  5  2  7  0  2  0  2  0  9 19 19  5  0  0  9 10  0 19  0
 19  9  7 19 18 19  5  9  7 12 15  9  7  9  7  9  9 12 12 15  9  0  5  2
  7  7 19 12  9 15  7 12 12 19 12  7  7  5  5  2  7  5  5  7  7  7  7  7
  7  7  7  9  7  7  7 19  7  7  7  8  7  7 12 19  9  3  3 12  6  5  5  5
 19 15  9  8  7 15 13  7  7  7  0  0  0  0  0 19 19  0  0  0  0  0  0  0
  9  2  9 15 15  0  2  5 15 15  5  8  2  9 15 10 10 15 15 15 12  9  9  9
  9  9  9  9  9  9  9  9  9  7  7  4  7 12  8  4 12 19  7  2 13 13 12  7
  7 12  0  9 19  0  1  9 19  9 19 20  5  5 18 19 18  9  8  8  5  9 19 15
 15 15 15 15 15 15 16 15 15  2  2  2  2  2  2  2  2 12  2  6  2  2  2  2
  2  2  2  2 15  2  9 15  2  7 19  2  5 13 15 15 15 15 15 15 13 15 15 15
 13 15 15 15 15 15 15 15 15 15  5 13 15 15  5  9  5 19 15  7  9 19 13 16
  2 11 16 12 13  5  9  7  7  7  5 12 12 12 12 12 12

In [107]:
y1

array([ 9,  9,  7,  7,  9,  9, 14,  5,  7,  7, 12,  9,  9,  9,  9,  7,  1,
        9,  5, 12,  7, 12, 14, 14, 12,  1, 12,  7,  7, 18,  5, 18,  5,  7,
        7, 14,  9,  7,  0,  9, 18,  7,  7,  7,  9,  9, 18, 12,  9, 12,  7,
       12, 18,  5,  1,  7,  0,  1,  0,  1,  0,  9, 18, 18,  5,  0,  0,  9,
       10,  0, 18,  0, 18,  9,  7, 18, 17, 18,  5,  9,  7, 12, 14,  9,  7,
        9,  7,  9,  9, 12, 12, 14,  9,  0,  5,  1,  7,  7, 18, 12,  9, 14,
        7, 12, 12, 18, 12,  7,  7,  5,  5,  1,  7,  5,  5,  7,  7,  7,  7,
        7,  7,  7,  7,  9,  7,  7,  7, 18,  7,  7,  7,  1,  7,  7, 12, 18,
        9,  5,  5, 12, 14,  5,  1,  5, 18, 14,  9,  5,  7, 14, 13,  7,  7,
        7,  0,  0,  0,  0,  0, 18, 18,  0,  0,  0,  0,  0,  0,  0,  9,  1,
        9, 14, 14,  0,  1,  5, 14, 14,  5,  5,  1,  9, 14,  9,  9, 14, 14,
       14, 12,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  7,  7,  3,
        7, 12,  8,  3, 12, 18,  7,  1,  5,  7, 12,  7, 12, 12,  0,  9, 18,
       17, 17,  9,  3,  9

In [108]:
y2

array([ 9,  9,  7,  7,  9,  9, 14,  5,  7,  7, 12,  9,  9,  9,  9,  7,  1,
        9,  5, 12,  7, 12, 14, 14, 12,  1, 12,  7,  7, 18,  5, 18,  5,  7,
        7, 14,  9,  7,  0,  9, 18,  7,  7,  7,  9,  9, 18, 12,  9, 12,  7,
       12, 18,  5,  1,  7,  0,  1,  0,  1,  0,  9, 18, 18,  5,  0,  0,  9,
       10,  0, 18,  0, 18,  9,  7, 18, 17, 18,  5,  9,  7, 12, 14,  9,  7,
        9,  7,  9,  9, 12, 12, 14,  9,  0,  5,  1,  7,  7, 18, 12,  9, 14,
        7, 12, 12, 18, 12,  7,  7,  5,  5,  1,  7,  5,  5,  7,  7,  7,  7,
        7,  7,  7,  7,  9,  7,  7,  7, 18,  7,  7,  7,  1,  7,  7, 12, 18,
        9,  5,  5, 12, 14,  5,  5,  5, 18, 14,  9,  5,  7, 14, 13,  7,  7,
        7,  0,  0,  0,  0,  0, 18, 18,  0,  0,  0,  0,  0,  0,  0,  9,  1,
        9, 14, 14,  0,  1,  5, 14, 14,  5,  5,  1,  9, 14,  9,  9, 14, 14,
       14, 12,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  7,  7,  3,
        7, 12,  8,  3, 12, 18,  7,  1,  5,  7, 12,  7,  5, 12,  0,  9, 18,
       17, 17,  9,  3,  9

In [109]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 4 2]
 [1.0 0.0 0.0 ... 1 4 7]
 [1.0 0.0 0.0 ... 1 4 0]
 ...
 [1.0 0.0 0.0 ... 1 4 4]
 [1.0 0.0 0.0 ... 0 4 10]
 [1.0 0.0 0.0 ... 0 4 1]]


# ***Spliting the data to testing and trainng***

In [128]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y3, test_size = 0.2, random_state = 0)

In [111]:
print(X_train)
print(X_train.shape)

[[1.0 0.0 0.0 ... 1 3 6]
 [1.0 0.0 0.0 ... 0 4 9]
 [1.0 0.0 0.0 ... 1 3 9]
 ...
 [1.0 0.0 0.0 ... 1 4 8]
 [1.0 0.0 0.0 ... 0 3 7]
 [1.0 0.0 0.0 ... 0 4 5]]
(640, 25)


In [129]:
print(X_test)
print(X_test.shape)

[[1.0 0.0 1.0 ... 1 3 5]
 [1.0 0.0 0.0 ... 1 4 2]
 [1.0 0.0 0.0 ... 1 4 0]
 ...
 [1.0 0.0 0.0 ... 1 4 8]
 [0.0 1.0 0.0 ... 0 3 9]
 [1.0 0.0 0.0 ... 0 4 4]]
(160, 25)


In [130]:
print(y_train)
print(y_train.shape)

[ 2  8  4  7  7  6  2  2  7  3  1  1  2  1  1  6  5  2  1  1  7  6  4  1
  4  2  3 10  8  1  3  6  7  1  6  8  2  1  6  9  1  2  8  2  3  6 10  6
  6  6  2  9  2  6  3  3  7  4  2  2  4  4  6  4  1  7  6 10  2  7  9  2
  2  9  4  1  2  9  7  2  7  1  1  2  4 10  1  2  1  7  6  3  3  3 10  4
  2  9  3  1  5  7  9  1  2  1  6  5  2  2  4  4  5  4  4  2  5  4  2  1
  1  1 10  6  1  4  2  1  7  2 10  1  1  2  6  2  4  7  9  7  9  3  9  4
  1  2  5  2  8  9  8  6  4  6  6  4  1  6  5  4  6  9 10  4  1  6  1 10
  7  3  9  7  4  6  7  2  1  2  1  1  2  6  3  9  6  1  1  1  1  7  4  2
  2  3  1  1  7  2  7  1 10  9  4  1  7  1  1  9  9  1  3  2 10  2  1  1
  1  1  3  6  4  9  7  2  9  2  2  1  7  7  1  6  1  2  6  1  9  1  1  5
  4  1  9  1  1  2  1  1  4  1  4  7  4  7 10  7  7  3  2  4  1  2  1  7
 10  1  3  4  4  1  6  3  1  3  6  2  5  1  5  7  3  1  3 10  6  9  4  1
  1  5  5  2  1  8  2  4  4  3 10  5  1  5  1  3  4  4 10  1  1  1  3  4
  2  2  2  2  5  9  9 10  2  6  1  2  6  1  6  1  2

In [131]:
print(y_test)
print(y_test.shape)

[ 4  7  6  7  2  2  4  6  1  7  6  2  8  1  1  1  7  8  5  1  1  4  4  2
  8  2  5  2  4  4  2  2  6  7  3  7  2  6  4  3  9  1  3  6  2  3  1  2
  9  4  1  2  3  7  3  1  2  2 10  4  9  1  9  6  2  5  2  4  3  1  7  3
  6  9  7  6  2  1  3  1  3  3  1  1  1  2  4 10  1  2 10  1  9  7  2  3
  2  1 10  3  7  2  1  6  4  1  1  7  2  1  1  1  1  8  2  2  2  6  6  1
  9  4  9  2  6  7  2  1  2  7  1  3  1  9  4  9  6  1 10 10  7  3  9  1
  3  1  3  5  9 10  4  1  1  3  6  6  1  9  3  2]
(160,)


# ***ANN***

In [132]:
import tensorflow as tf

In [133]:
tf.__version__

'2.7.0'

**Feature Scaling**

In [134]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# ***Build ANN***

In [135]:
ann = tf.keras.models.Sequential()

In [136]:
ann.add(tf.keras.layers.Dense(units=24, activation='relu'))

In [137]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [138]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [144]:
ann.fit(X_train, y_train, batch_size = 50, epochs = 500)

Epoch 1/500
13/13 [==============================] - 0s 3ms/step - loss: -214963.5938 - accuracy: 0.2422
Epoch 2/500
13/13 [==============================] - 0s 3ms/step - loss: -215101.1250 - accuracy: 0.2422
Epoch 3/500
13/13 [==============================] - 0s 3ms/step - loss: -215239.2969 - accuracy: 0.2422
Epoch 4/500
13/13 [==============================] - 0s 3ms/step - loss: -215376.4219 - accuracy: 0.2422
Epoch 5/500
13/13 [==============================] - 0s 3ms/step - loss: -215517.2188 - accuracy: 0.2422
Epoch 6/500
13/13 [==============================] - 0s 3ms/step - loss: -215653.4531 - accuracy: 0.2422
Epoch 7/500
13/13 [==============================] - 0s 2ms/step - loss: -215792.0469 - accuracy: 0.2422
Epoch 8/500
13/13 [==============================] - 0s 2ms/step - loss: -215932.2031 - accuracy: 0.2422
Epoch 9/500
13/13 [==============================] - 0s 2ms/step - loss: -216070.2969 - accuracy: 0.2422
Epoch 10/500
13/13 [==============================] - 0

# ***Naive Bayes***

In [145]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [141]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 9  4]
 [10  7]
 [ 5  6]
 [ 5  7]
 [ 9  2]
 [10  2]
 [ 8  4]
 [10  6]
 [10  1]
 [10  7]
 [ 5  6]
 [ 5  2]
 [10  8]
 [ 5  1]
 [10  1]
 [ 5  1]
 [ 5  7]
 [10  8]
 [ 5  5]
 [ 5  1]
 [10  1]
 [ 8  4]
 [10  4]
 [ 5  2]
 [10  8]
 [10  2]
 [10  5]
 [ 5  2]
 [ 8  4]
 [ 5  4]
 [ 9  2]
 [ 8  2]
 [ 5  6]
 [ 8  7]
 [ 8  3]
 [ 5  7]
 [ 9  2]
 [ 5  6]
 [10  4]
 [ 5  3]
 [ 5  9]
 [ 5  1]
 [ 7  3]
 [10  6]
 [10  2]
 [ 5  3]
 [ 5  1]
 [ 9  2]
 [ 5  9]
 [ 9  4]
 [10  1]
 [ 7  2]
 [ 8  3]
 [ 5  7]
 [ 5  3]
 [ 9  1]
 [ 9  2]
 [ 5  2]
 [10 10]
 [ 8  4]
 [10  9]
 [ 5  1]
 [ 9  9]
 [10  6]
 [ 5  2]
 [10  5]
 [10  2]
 [ 9  4]
 [ 8  3]
 [ 9  1]
 [ 7  7]
 [10  3]
 [ 5  6]
 [ 9  9]
 [10  7]
 [ 5  6]
 [ 9  2]
 [10  1]
 [10  3]
 [ 5  1]
 [ 8  3]
 [ 8  3]
 [ 5  1]
 [10  1]
 [ 5  1]
 [ 9  2]
 [ 8  4]
 [10 10]
 [ 5  1]
 [10  2]
 [10 10]
 [10  1]
 [ 9  9]
 [ 8  7]
 [ 8  2]
 [ 5  3]
 [10  2]
 [10  1]
 [10 10]
 [ 8  3]
 [ 8  7]
 [ 5  2]
 [ 5  1]
 [10  6]
 [ 5  4]
 [ 5  1]
 [ 8  1]
 [ 8  7]
 [ 7  2]
 [ 5  1]
 [10  1]
 

In [142]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0 21  0  0  1  4 11]
 [ 0  0  0  0 10  0  2  2  8  8]
 [ 0  0  2  0  5  0  1  7  1  3]
 [ 0  0  0  0  4  0  1  5  3  2]
 [ 0  0  0  0  1  0  0  0  0  3]
 [ 0  0  0  0  9  0  0  1  1  5]
 [ 0  0  0  0  5  0  1  5  0  4]
 [ 0  0  0  0  0  0  0  0  0  4]
 [ 0  0  0  0  6  0  0  0  4  3]
 [ 0  0  0  0  0  0  0  0  0  7]]


0.09375