<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Lyrics_Classification_Ensemble_methods(Dataset5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2/Ensemble Methods

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2/Ensemble Methods


In [30]:
dataset = pd.read_csv('Lyrical_data_5.csv',encoding='cp1252')

In [31]:
dataset.dropna(how='all', axis=1, inplace=True)

In [32]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...         Love
4        5  ...         Love

[5 rows x 4 columns]

In [33]:
lyrics2 = dataset['Chorus']
lyrics2

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
795    You've got every right\r\nTo a beautiful life\...
796    I'm only one call away\r\nI'll be there to sav...
797    It started with a kiss on your mama's couch\r\...
798    I warned myself that I shouldn't play with fir...
799    I'll admit, I was wrong, what else can I say, ...
Name: Chorus, Length: 800, dtype: object

Checking the empty rows in dataset

In [34]:
print (dataset.isnull().sum())

Song_ID       0
Song_Title    0
Chorus        0
Emotion       0
dtype: int64


In [35]:
modifiedDF = dataset.dropna()
modifiedDF

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...         Love
4          5  ...         Love
..       ...  ...          ...
795      796  ...  Inspiration
796      797  ...  Inspiration
797      798  ...          Sad
798      799  ...          Sad
799      800  ...          Sad

[800 rows x 4 columns]

In [36]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 799):
  Lyrics = re.sub('[^a-zA-Z]', ' ', modifiedDF['Chorus'][i])
  Lyrics = Lyrics.lower()
  Lyrics = Lyrics.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove('down')
  all_stopwords.remove('over')
  all_stopwords.remove('under')
  all_stopwords.remove('no')
  all_stopwords.remove('only')
  all_stopwords.remove("don't")
  all_stopwords.remove("aren't")
  all_stopwords.remove("y")
  all_stopwords.remove("i")
  all_stopwords.remove("o")
  all_stopwords.remove("ma")
  all_stopwords.remove("didn't")
  all_stopwords.remove("can")
  all_stopwords.remove("be")
  all_stopwords.remove("to")
  all_stopwords.remove("for")
  all_stopwords.remove("you")
  all_stopwords.remove("your")
  all_stopwords.remove("we")
  all_stopwords.remove("our")
  all_stopwords.remove("my")
  all_stopwords.remove("you're")
  Lyrics = [ps.stem(word) for word in Lyrics if not word in set(all_stopwords)]
  Lyrics = ' '.join(Lyrics)
  corpus.append(Lyrics)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Creating the bag of words modal

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = modifiedDF.iloc[0:799, -1].values

Splitting the dataset into the Training set and Test set

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 8)


# Ensemble Methods

Bagging meta-estimator

In [39]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
classifier = BaggingClassifier(KNeighborsClassifier(),max_samples=0.6, max_features=0.2)
classifier.fit(X_train, y_train)

BaggingClassifier(base_estimator=KNeighborsClassifier(), max_features=0.2,
                  max_samples=0.6)

Predicting the Test set results

In [40]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Happy' 'Love']
 ['Inspiration' 'Inspiration']
 ['Sad' 'Happy']
 ['Inspiration' 'Sad']
 ['Sad' 'Sad']
 ['Happy' 'Sad']
 ['Sad' 'Sad']
 ['Sad' 'Sad']
 ['Happy' 'Inspiration']
 ['Inspiration' 'Sad']
 ['Sad' 'Sad']
 ['Angry' 'Love']
 ['Love' 'Sad']
 ['Sad' 'Love']
 ['Happy' 'Happy']
 ['Inspiration' 'Sad']
 ['Inspiration' 'Love']
 ['Inspiration' 'Sad']
 ['Sad' 'Inspiration']
 ['Love' 'Sad']
 ['Inspiration' 'Sad']
 ['Sad' 'Sad']
 ['Happy' 'Happy']
 ['Inspiration' 'Love']
 ['Happy' 'Inspiration']
 ['Sad' 'Calm']
 ['Sad' 'Sad']
 ['Happy' 'Happy']
 ['Happy' 'Love']
 ['Inspiration' 'Inspiration']
 ['Happy' 'Inspiration']
 ['Sad' 'Sad']
 ['Sad' 'Love']
 ['Sad' 'Calm']
 ['Sad' 'Love']
 ['Sad' 'Happy']
 ['Inspiration' 'Inspiration']
 ['Sad' 'Sad']
 ['Sad' 'Inspiration']
 ['Sad' 'Happy']
 ['Sad' 'Love']
 ['Sad' 'Love']
 ['Happy' 'Calm']
 ['Happy' 'Happy']
 ['Happy' 'Sad']
 ['Calm' 'Inspiration']
 ['Sad' 'Love']
 ['Sad' 'Happy']
 ['Happy' 'Calm']
 ['Sad' 'Sad']
 ['Happy' 'Angry']
 ['Happy' 'Sad']


Making the Confusion Matrix

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  4  1  1  2]
 [ 0  1 12  1  1  4]
 [ 1  1 13  3  2 10]
 [ 0  2 10  6  2  6]
 [ 1  0  7  5  4 11]
 [ 0  2  7 12  3 25]]


0.30625

Appyling K-fold cross validation

In [42]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 34.43 %
Standard Deviation: 1.45 %


In [43]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 31.30 %
Standard Deviation: 4.95 %


In [44]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 8)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 30.04 %
Standard Deviation: 4.11 %


Extremely Randomized Trees

In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=10, min_samples_split=10,random_state=10)
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores.mean()

0.35826771653543305

In [46]:

clf2 = RandomForestClassifier(n_estimators=60, max_depth=None,min_samples_split=2, random_state=5)
scores = cross_val_score(clf2, X_train, y_train, cv=10)
scores.mean()

0.4805059523809524

In [47]:
clf3 = ExtraTreesClassifier(n_estimators=40, max_depth=None,min_samples_split=6, random_state=10)
scores = cross_val_score(clf3, X_train, y_train, cv=5)
scores.mean()

0.45228838582677167

Fit an AdaBoost classifier with 100 weak learners:



In [48]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(n_estimators=10)
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores.mean()

0.3396577380952381

Gradient Tree Boosting

In [49]:
from sklearn.ensemble import GradientBoostingClassifier

clf5 = GradientBoostingClassifier(n_estimators=10, learning_rate=2.5,max_depth=None, random_state=42).fit(X_train, y_train)
clf5.score(X_test, y_test)

0.40625

Cross validation

In [50]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = clf5, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 37.72 %
Standard Deviation: 3.49 %


HistGradientBoostingClassifier

In [51]:
from sklearn.ensemble import HistGradientBoostingClassifier

gbdt = HistGradientBoostingClassifier(categorical_features=[1,2,3,4,5,6], min_samples_leaf=10).fit(X_train, y_train)
gbdt.score(X_test, y_test)

0.50625

# Voting Classifiers

In [52]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

clf10 = LogisticRegression(random_state=10)
clf20 = RandomForestClassifier(n_estimators=50, random_state=10)
clf30 = GaussianNB()

eclf = VotingClassifier(estimators=[('lr', clf10), ('rf', clf20), ('gnb', clf30)],voting='hard')

for clf, label in zip([clf10, clf20, clf30, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
  scores = cross_val_score(clf, X_train, y_train, scoring='accuracy', cv=10)
  print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Accuracy: 0.45 (+/- 0.04) [Logistic Regression]
Accuracy: 0.45 (+/- 0.04) [Random Forest]
Accuracy: 0.32 (+/- 0.07) [naive Bayes]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Accuracy: 0.45 (+/- 0.06) [Ensemble]


In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from itertools import product
from sklearn.ensemble import VotingClassifier

# Training classifiers
clf1 = DecisionTreeClassifier(max_depth=4)
clf2 = KNeighborsClassifier(n_neighbors=8)
clf3 = SVC(kernel='rbf', probability=True)
eclf = VotingClassifier(estimators=[('dt', clf1), ('knn', clf2), ('svc', clf3)],voting='soft', weights=[2, 1, 2])

clf1 = clf1.fit(X_train, y_train)
clf2 = clf2.fit(X_train, y_train)
clf3 = clf3.fit(X_train, y_train)
eclf = eclf.fit(X_train, y_train)

for clf, label in zip([clf1, clf2, clf3, eclf], ['DT', 'KNN', 'SVC', 'Ensemble']):
  scores = cross_val_score(clf, X_train, y_train, scoring='accuracy', cv=10)
  print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

Accuracy: 0.36 (+/- 0.05) [DT]
Accuracy: 0.31 (+/- 0.05) [KNN]
Accuracy: 0.40 (+/- 0.05) [SVC]
Accuracy: 0.46 (+/- 0.05) [Ensemble]


Using the VotingClassifier with GridSearchCV

In [54]:
from sklearn.model_selection import GridSearchCV
clf1 = LogisticRegression(random_state=10)
clf2 = RandomForestClassifier(random_state=10)
clf3 = GaussianNB()
eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)],voting='soft')

params = {'lr__C': [1.0, 100.0], 'rf__n_estimators': [20, 200]}

grid = GridSearchCV(estimator=eclf, param_grid=params, cv=10)
grid = grid.fit(X_train, y_train)
print("grid.best_score_", grid.best_score_)
grid.best_params_

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


grid.best_score_ 0.4225446428571429


{'lr__C': 100.0, 'rf__n_estimators': 200}