<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Lyrics_Classification_NB_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
pwd

'/content/drive/My Drive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2'

In [18]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2


In [19]:
pwd

'/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2'

In [20]:
dataset = pd.read_csv('Lyrical_data_2.csv',encoding='cp1252')

In [21]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [22]:
lyrics = dataset['Chorus']
lyrics

0      Diana,\r\nLet me be the one to light a fire in...
1      Don't forget where you belong\r\nHome\r\nDon't...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\r\nMore than a feeling \r\nC...
                             ...                        
276    Anyway I'm just gonna sing and play\nUm, and I...
277    Heart beats fast\r\nColors and promises\r\nHow...
278    It's a pity\r\nLow down and dirty shame\r\nLor...
279    I went down to the river\r\nSat there all nigh...
280    You think that you have left me behind\r\nAnd ...
Name: Chorus, Length: 281, dtype: object

In [23]:
dataset.dropna(how='all', axis=1, inplace=True)

In [24]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [25]:
dataset

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
276      277  ...         Love
277      278  ...         Love
278      279  ...        Angry
279      280  ...          Sad
280      281  ...          Sad

[281 rows x 4 columns]

In [27]:
lyrics2 = dataset['Chorus']
lyrics2

0      Diana,\r\nLet me be the one to light a fire in...
1      Don't forget where you belong\r\nHome\r\nDon't...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\r\nMore than a feeling \r\nC...
                             ...                        
276    Anyway I'm just gonna sing and play\nUm, and I...
277    Heart beats fast\r\nColors and promises\r\nHow...
278    It's a pity\r\nLow down and dirty shame\r\nLor...
279    I went down to the river\r\nSat there all nigh...
280    You think that you have left me behind\r\nAnd ...
Name: Chorus, Length: 281, dtype: object

Checking the empty rows in dataset

In [28]:
print (dataset.isnull().sum())

Song_ID       0
Song_Title    0
Chorus        1
Emotion       2
dtype: int64


In [29]:
modifiedDF = dataset.dropna()
modifiedDF

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
276      277  ...         Love
277      278  ...         Love
278      279  ...        Angry
279      280  ...          Sad
280      281  ...          Sad

[279 rows x 4 columns]

In [51]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 34):
  Lyrics = re.sub('[^a-zA-Z]', ' ', modifiedDF['Chorus'][i])
  Lyrics = Lyrics.lower()
  Lyrics = Lyrics.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  Lyrics = [ps.stem(word) for word in Lyrics if not word in set(all_stopwords)]
  Lyrics = ' '.join(Lyrics)
  corpus.append(Lyrics)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Print corpus

In [52]:
print(corpus)

['diana let one light fire insid eye lone even know feel cri diana let one lift heart save life think even realiz babi save mine', 'forget belong home forget belong home ever feel alon never proof song', 'sorri say need care not scare love caus not weaker wrong wrong make strong', 'care peopl say togeth know wanna one hold sleep want forev know wanna leav c mon babi happili', 'better word feel crazi love danc ceil everi time touch shook make wanna deep love god know babi', 'tell hurt vain see heart love rememb laugh let laugh burn even scream shout come back back oh carri fire water love hold closer hope heart strong enough night come find way dark', 'know know know know everi everi everi time lone sometim wanna cave wanna fight tri tri tri tri tri hold lone momma sorri not sober anymor daddi pleas forgiv drink spill floor one never left road sorri not sober anymor not sober anymor sorri promis get help intent sorri', 'walk th park saw anoth arm month apart look happier saw walk insid 

Creating the bag of words modal

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = modifiedDF.iloc[0:34, -1].values

In [54]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [55]:
y

array(['Inspiration', 'Inspiration', 'Inspiration', 'Sad', 'Love',
       'Inspiration', 'Sad', 'Sad', 'Sad', 'Happy', 'Love', 'Inspiration',
       'Love', 'Inspiration', 'Inspiration', 'Angry', 'Inspiration',
       'Angry', 'Sad', 'Love', 'Sad', 'Inspiration', 'Sad', 'Sad', 'Love',
       'Sad', 'Love', 'Sad', 'Calm', 'Tense', 'Love', 'Inspiration',
       'Love', 'Love'], dtype=object)

Splitting the dataset into the Training set and Test set

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

Training the Naive Bayes model on the Training set

In [57]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

Predicting the Test set results

In [58]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Inspiration' 'Inspiration']
 ['Love' 'Sad']
 ['Sad' 'Sad']
 ['Sad' 'Angry']
 ['Sad' 'Inspiration']
 ['Sad' 'Love']
 ['Sad' 'Inspiration']]


Making the Confusion Matrix

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 1]
 [0 1 0 2]
 [0 0 0 1]
 [0 0 1 1]]


0.2857142857142857

Stop words

In [39]:
all_stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

Appyling K-fold cross validation

In [71]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 37.04 %
Standard Deviation: 5.24 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  UserWarning,


In [72]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 34.00 %
Standard Deviation: 9.04 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


In [73]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 8)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 34.38 %
Standard Deviation: 21.01 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=8.
  UserWarning,
