<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Lyrics_Classification_RF_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pwd

'/content'

In [3]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2


In [4]:
pwd

'/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2'

In [5]:
dataset = pd.read_csv('Lyrical_data_3.csv',encoding='cp1252')

In [6]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [7]:
lyrics = dataset['Chorus']
lyrics

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
795    You've got every right\r\nTo a beautiful life\...
796    I'm only one call away\r\nI'll be there to sav...
797    It started with a kiss on your mama's couch\r\...
798    I warned myself that I shouldn't play with fir...
799    I'll admit, I was wrong, what else can I say, ...
Name: Chorus, Length: 800, dtype: object

In [8]:
dataset.dropna(how='all', axis=1, inplace=True)

In [9]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [10]:
dataset

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
795      796  ...  Inspiration
796      797  ...  Inspiration
797      798  ...          Sad
798      799  ...          Sad
799      800  ...          Sad

[800 rows x 4 columns]

In [11]:
lyrics2 = dataset['Chorus']
lyrics2

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
795    You've got every right\r\nTo a beautiful life\...
796    I'm only one call away\r\nI'll be there to sav...
797    It started with a kiss on your mama's couch\r\...
798    I warned myself that I shouldn't play with fir...
799    I'll admit, I was wrong, what else can I say, ...
Name: Chorus, Length: 800, dtype: object

Checking the empty rows in dataset

In [12]:
print (dataset.isnull().sum())

Song_ID       0
Song_Title    0
Chorus        0
Emotion       0
dtype: int64


In [13]:
modifiedDF = dataset.dropna()
modifiedDF

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
795      796  ...  Inspiration
796      797  ...  Inspiration
797      798  ...          Sad
798      799  ...          Sad
799      800  ...          Sad

[800 rows x 4 columns]

In [14]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 799):
  Lyrics = re.sub('[^a-zA-Z]', ' ', modifiedDF['Chorus'][i])
  Lyrics = Lyrics.lower()
  Lyrics = Lyrics.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove('down')
  all_stopwords.remove('over')
  all_stopwords.remove('under')
  all_stopwords.remove('no')
  all_stopwords.remove('only')
  all_stopwords.remove("don't")
  all_stopwords.remove("aren't")
  Lyrics = [ps.stem(word) for word in Lyrics if not word in set(all_stopwords)]
  Lyrics = ' '.join(Lyrics)
  corpus.append(Lyrics)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Print corpus

In [15]:
print(corpus)

['diana let one light fire insid eye lone even know feel cri diana let one lift heart save life think even realiz babi save mine', 'forget belong home forget belong home ever feel alon never proof song', 'sorri say need care not scare love caus not weaker wrong wrong make strong', 'care peopl say togeth know wanna one hold sleep want forev know wanna leav c mon babi happili', 'better word feel crazi love danc ceil everi time touch shook make wanna deep love god onli know babi', 'tell hurt vain see heart love rememb laugh let laugh burn even scream shout come back back oh carri over fire water love hold closer hope heart strong enough night come down find way dark', 'know know know know everi everi everi time onli lone sometim wanna cave wanna fight tri tri tri tri tri hold lone momma sorri not sober anymor daddi pleas forgiv drink spill floor one never left down road sorri not sober anymor not sober anymor sorri promis get help intent sorri', 'walk down th park saw anoth arm onli month

Creating the bag of words modal

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = modifiedDF.iloc[0:799, -1].values

In [17]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
y

array(['Inspiration', 'Inspiration', 'Inspiration', 'Sad', 'Love',
       'Inspiration', 'Sad', 'Sad', 'Sad', 'Happy', 'Love', 'Inspiration',
       'Love', 'Inspiration', 'Inspiration', 'Angry', 'Inspiration',
       'Angry', 'Sad', 'Love', 'Sad', 'Inspiration', 'Sad', 'Sad', 'Love',
       'Sad', 'Love', 'Sad', 'Calm', 'Angry', 'Love', 'Inspiration',
       'Love', 'Love', 'Angry', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad',
       'Happy', 'Happy', 'Love', 'Inspiration', 'Love', 'Calm', 'Sad',
       'Inspiration', 'Love', 'Inspiration', 'Love', 'Inspiration',
       'Love', 'Inspiration', 'Inspiration', 'Love', 'Calm', 'Angry',
       'Inspiration', 'Angry', 'Angry', 'Angry', 'Love', 'Inspiration',
       'Sad', 'Sad', 'Inspiration', 'Inspiration', 'Happy', 'Angry',
       'Inspiration', 'Sad', 'Inspiration', 'Sad', 'Inspiration', 'Sad',
       'Sad', 'Calm', 'Inspiration', 'Love', 'Love', 'Sad', 'Inspiration',
       'Inspiration', 'Inspiration', 'Love', 'Inspiration', 'Inspiration'

Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Random Forest Classification model on the Training set

In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=0)

Predicting the Test set results

In [21]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Happy' 'Calm']
 ['Sad' 'Inspiration']
 ['Calm' 'Happy']
 ['Sad' 'Sad']
 ['Inspiration' 'Happy']
 ['Love' 'Love']
 ['Sad' 'Sad']
 ['Sad' 'Sad']
 ['Angry' 'Angry']
 ['Calm' 'Calm']
 ['Inspiration' 'Inspiration']
 ['Love' 'Sad']
 ['Sad' 'Angry']
 ['Calm' 'Happy']
 ['Sad' 'Sad']
 ['Inspiration' 'Inspiration']
 ['Calm' 'Calm']
 ['Inspiration' 'Inspiration']
 ['Sad' 'Angry']
 ['Sad' 'Happy']
 ['Inspiration' 'Sad']
 ['Sad' 'Happy']
 ['Inspiration' 'Inspiration']
 ['Love' 'Sad']
 ['Sad' 'Love']
 ['Calm' 'Sad']
 ['Love' 'Angry']
 ['Sad' 'Love']
 ['Love' 'Love']
 ['Love' 'Love']
 ['Sad' 'Calm']
 ['Happy' 'Calm']
 ['Inspiration' 'Inspiration']
 ['Love' 'Love']
 ['Calm' 'Calm']
 ['Sad' 'Inspiration']
 ['Sad' 'Sad']
 ['Sad' 'Happy']
 ['Sad' 'Angry']
 ['Love' 'Inspiration']
 ['Happy' 'Happy']
 ['Sad' 'Inspiration']
 ['Sad' 'Inspiration']
 ['Happy' 'Happy']
 ['Sad' 'Calm']
 ['Sad' 'Calm']
 ['Calm' 'Calm']
 ['Sad' 'Sad']
 ['Happy' 'Love']
 ['Love' 'Love']
 ['Inspiration' 'Love']
 ['Love' 'Love']
 [

Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 2  1  2  0  1  5]
 [ 0  5  2  2  0  8]
 [ 0  2 11  2  2  9]
 [ 0  2  4  8  5 14]
 [ 0  1  4  1 15  8]
 [ 0  5  4  1  8 26]]


0.41875

Appyling K-fold cross validation

In [23]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 2)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 42.72 %
Standard Deviation: 0.09 %


In [24]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 43.51 %
Standard Deviation: 0.96 %


In [25]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 4)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 43.97 %
Standard Deviation: 0.82 %


In [26]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 44.91 %
Standard Deviation: 2.45 %


In [27]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 6)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 45.24 %
Standard Deviation: 3.18 %


In [28]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 7)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 43.03 %
Standard Deviation: 3.20 %


In [29]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 8)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 44.44 %
Standard Deviation: 3.19 %


In [30]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 45.39 %
Standard Deviation: 6.83 %


## Applying Grid Search to find the best model and the best parameters

In [31]:
from sklearn.model_selection import GridSearchCV
parameters = [{'criterion' : ['entropy','gini'], 'n_estimators' : [10,20,40,50,80,100,120,140,150,200]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 46.96 %
Best Parameters: {'criterion': 'gini', 'n_estimators': 80}
