<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Lyrics_Classification_NB(Dataset5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [362]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [363]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2/NB

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2/NB


In [364]:
dataset = pd.read_csv('Lyrical_data_5.csv',encoding='cp1252')

In [365]:
dataset.dropna(how='all', axis=1, inplace=True)

Checking the empty rows in dataset

In [366]:
print (dataset.isnull().sum())

Song_ID       0
Song_Title    0
Chorus        0
Emotion       0
dtype: int64


In [367]:
modifiedDF = dataset.dropna()

In [368]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 799):
  Lyrics = re.sub('[^a-zA-Z]', ' ', modifiedDF['Chorus'][i])
  Lyrics = Lyrics.lower()
  Lyrics = Lyrics.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove('down')
  all_stopwords.remove('over')
  all_stopwords.remove('under')
  all_stopwords.remove('no')
  all_stopwords.remove('only')
  all_stopwords.remove("don't")
  all_stopwords.remove("aren't")
  all_stopwords.remove("y")
  all_stopwords.remove("i")
  all_stopwords.remove("o")
  all_stopwords.remove("ma")
  all_stopwords.remove("didn't")
  all_stopwords.remove("can")
  all_stopwords.remove("be")
  all_stopwords.remove("to")
  all_stopwords.remove("for")
  all_stopwords.remove("you")
  all_stopwords.remove("your")
  all_stopwords.remove("we")
  all_stopwords.remove("our")
  all_stopwords.remove("my")
  all_stopwords.remove("you're")
  Lyrics = [ps.stem(word) for word in Lyrics if not word in set(all_stopwords)]
  Lyrics = ' '.join(Lyrics)
  corpus.append(Lyrics)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Creating the bag of words modal

In [369]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1150)
X = cv.fit_transform(corpus).toarray()
y = modifiedDF.iloc[0:799, -1].values

Splitting the dataset into the Training set and Test set

In [370]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

Training the Naive Bayes model on the Training set

In [371]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

Predicting the Test set results

In [372]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Sad' 'Sad']
 ['Inspiration' 'Angry']
 ['Calm' 'Happy']
 ['Happy' 'Inspiration']
 ['Love' 'Sad']
 ['Love' 'Sad']
 ['Happy' 'Happy']
 ['Calm' 'Sad']
 ['Angry' 'Angry']
 ['Sad' 'Love']
 ['Sad' 'Inspiration']
 ['Happy' 'Love']
 ['Inspiration' 'Inspiration']
 ['Love' 'Sad']
 ['Happy' 'Happy']
 ['Love' 'Sad']
 ['Sad' 'Sad']
 ['Happy' 'Happy']
 ['Sad' 'Sad']
 ['Love' 'Sad']
 ['Sad' 'Sad']
 ['Happy' 'Happy']
 ['Inspiration' 'Love']
 ['Sad' 'Sad']
 ['Angry' 'Inspiration']
 ['Inspiration' 'Calm']
 ['Sad' 'Love']
 ['Sad' 'Love']
 ['Love' 'Love']
 ['Love' 'Sad']
 ['Calm' 'Love']
 ['Love' 'Love']
 ['Inspiration' 'Sad']
 ['Sad' 'Happy']
 ['Angry' 'Happy']
 ['Love' 'Happy']
 ['Inspiration' 'Sad']
 ['Inspiration' 'Inspiration']
 ['Calm' 'Love']
 ['Sad' 'Sad']
 ['Sad' 'Sad']
 ['Angry' 'Sad']
 ['Calm' 'Calm']
 ['Happy' 'Inspiration']
 ['Inspiration' 'Sad']
 ['Inspiration' 'Love']
 ['Love' 'Love']
 ['Happy' 'Calm']
 ['Angry' 'Angry']
 ['Love' 'Love']
 ['Happy' 'Love']
 ['Sad' 'Angry']
 ['Love' 'Sad']


Making the Confusion Matrix

In [373]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  0  2  1  1  3]
 [ 0  5  2  5  0  3]
 [ 1  1  7  4  2  4]
 [ 3  1  2 14  6  6]
 [ 0  4  3  5 14  4]
 [ 5  1  2 12 13 18]]


0.4

Appyling K-fold cross validation

In [374]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 32.55 %
Standard Deviation: 0.59 %


In [375]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 30.68 %
Standard Deviation: 1.43 %


In [376]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 4)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 29.11 %
Standard Deviation: 1.79 %


In [377]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 8)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 30.68 %
Standard Deviation: 2.90 %


In [378]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 31.77 %
Standard Deviation: 5.59 %
