<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Lyrics_Classification_NLP_Method_2_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://towardsdatascience.com/natural-language-processing-nlp-for-machine-learning-d44498845d5b


https://github.com/supuni9622/Natural-Language-Processing-NLP-for-Machine-Learning

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pwd

'/content'

In [4]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2


In [5]:
pwd

'/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2'

In [6]:
dataset = pd.read_csv('Lyrical_data_2.csv',encoding='cp1252')

In [7]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [10]:
lyrics = dataset['Chorus']
lyrics

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
276    Anyway I'm just gonna sing and play\nUm, and I...
277    Heart beats fast\rColors and promises\rHow to ...
278    It's a pity\rLow down and dirty shame\rLord, i...
279    I went down to the river\rSat there all night ...
280    You think that you have left me behind\rAnd th...
Name: Chorus, Length: 281, dtype: object

In [11]:
dataset.dropna(how='all', axis=1, inplace=True)

In [12]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [13]:
dataset

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
276      277  ...         Love
277      278  ...         Love
278      279  ...        Angry
279      280  ...          Sad
280      281  ...          Sad

[281 rows x 4 columns]

In [14]:
lyrics2 = dataset['Chorus']
lyrics2

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
276    Anyway I'm just gonna sing and play\nUm, and I...
277    Heart beats fast\rColors and promises\rHow to ...
278    It's a pity\rLow down and dirty shame\rLord, i...
279    I went down to the river\rSat there all night ...
280    You think that you have left me behind\rAnd th...
Name: Chorus, Length: 281, dtype: object

Checking the empty rows in dataset

In [16]:
print (dataset.isnull().sum())

Song_ID       0
Song_Title    0
Chorus        1
Emotion       2
dtype: int64


In [17]:
modifiedDF = dataset.dropna()
modifiedDF

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
276      277  ...         Love
277      278  ...         Love
278      279  ...        Angry
279      280  ...          Sad
280      281  ...          Sad

[279 rows x 4 columns]

In [20]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Remove punctuation

In [21]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [22]:
def remove_punct(text):
  text_nopunct = "".join({char for char in text if char not in string.punctuation})
  return text_nopunct

modifiedDF['Chorus_Cleaned'] = modifiedDF['Chorus'].apply(lambda x: remove_punct(x)) 

modifiedDF.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Song_ID  ...                      Chorus_Cleaned
0        1  ...     ibYpvz\rl tDIwLouehBcrydksnmagf
1        2  ...        biYpv\rl tDIwouHehrydsnAmagf
2        3  ...         iTvl Itw\noueBchrydksnCmagf
3        4  ...       biYpv\rl SItwoujehcrydksnmagf
4        5  ...  ibYpvz\rl tDIwoueBhcrydkMsnEGCmagf

[5 rows x 5 columns]

Tokenization : Tokenizing separates text into units such as sentences or words. It gives structure to previously unstructured text. eg: Plata o Plomo-> ‘Plata’,’o’,’Plomo’.

In [26]:
import re

#Function to tokenize words
def tokenize(text):
  tokens = re.split('\W+', text) #W+ means that either a word character (A-Za-z0-9) or a dash (-) can go there
  return tokens

modifiedDF['Chorus_tokenized'] = modifiedDF['Chorus'].apply(lambda x: tokenize(x.lower()))

modifiedDF.head()


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Song_ID  ...                                   Chorus_tokenized
0        1  ...  [diana, let, me, be, the, one, to, light, a, f...
1        2  ...  [don, t, forget, where, you, belong, home, don...
2        3  ...  [i, m, sorry, if, i, say, i, need, you, but, i...
3        4  ...  [i, don, t, care, what, people, say, when, we,...
4        5  ...  [better, than, words, more, than, a, feeling, ...

[5 rows x 6 columns]

Remove stopwords

In [34]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stopwords = stopwords.words('english') #All english stop words
stopwords.remove('not')
stopwords.remove('down')
stopwords.remove('up')
stopwords.remove('in')
stopwords.remove('with')
stopwords.remove('you')
stopwords.remove('why')
# nltk.download('stopwords')
# from nltk.corpus import stopwords
# from nltk.stem.porter import PorterStemmer
# corpus = []
# for i in range(0, 34):
#   Lyrics = re.sub('[^a-zA-Z]', ' ', modifiedDF['Chorus'][i])
#   Lyrics = Lyrics.lower()
#   Lyrics = Lyrics.split()
#   ps = PorterStemmer()
#   all_stopwords = stopwords.words('english')
#   all_stopwords.remove('not')
#   Lyrics = [ps.stem(word) for word in Lyrics if not word in set(all_stopwords)]
#   Lyrics = ' '.join(Lyrics)
#   corpus.append(Lyrics)

#Function to remove stopwords
def remove_stopwords(tokernized_list):
  text = [word for word in tokernized_list if word not in stopwords] 
  return text

modifiedDF['Chorus_nostop'] = modifiedDF['Chorus_tokenized'].apply(lambda x: remove_stopwords(x))

modifiedDF.head()


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


Song_ID  ...                                      Chorus_nostop
0        1  ...  [diana, let, one, light, fire, inside, eyes, y...
1        2  ...  [forget, you, belong, home, forget, you, belon...
2        3  ...  [sorry, say, need, you, care, not, scared, lov...
3        4  ...  [care, people, say, together, you, know, wanna...
4        5  ...  [better, words, feeling, crazy, in, love, danc...

[5 rows x 7 columns]

Stemming : Stemming helps reduce a word to its stem form. It often makes sense to treat related words in the same way. It removes suffices, like “ing”, “ly”, “s”, etc. by a simple rule-based approach. It reduces the corpus of words but often the actual words get neglected. 

In [36]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stemming(tokernized_text):
  text = [ps.stem(word) for word in tokernized_text]
  return text

modifiedDF['Chorus_nostop_stemmed'] = modifiedDF['Chorus_nostop'].apply(lambda x: stemming(x))
modifiedDF['Chorus_stemmed'] = modifiedDF['Chorus_tokenized'].apply(lambda x: stemming(x))

modifiedDF.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


Song_ID  ...                                     Chorus_stemmed
0        1  ...  [diana, let, me, be, the, one, to, light, a, f...
1        2  ...  [don, t, forget, where, you, belong, home, don...
2        3  ...  [i, m, sorri, if, i, say, i, need, you, but, i...
3        4  ...  [i, don, t, care, what, peopl, say, when, we, ...
4        5  ...  [better, than, word, more, than, a, feel, craz...

[5 rows x 9 columns]

#Lemmatizing:
Lemmatizing derives the canonical form (‘lemma’) of a word. i.e the root form. It is better than stemming as it uses a dictionary-based approach i.e a morphological analysis to the root word.eg: Entitling, Entitled->Entitle
In Short, Stemming is typically faster as it simply chops off the end of the word, without understanding the context of the word. Lemmatizing is slower and more accurate as it takes an informed analysis with the context of the word in mind.

In [39]:
import nltk
nltk.download('wordnet')
wn = nltk.WordNetLemmatizer()

def lematizing(tokenized_text):
  text = [wn.lemmatize(word) for word in tokenized_text]
  return text

modifiedDF['Chorus_nostop_lematized'] = modifiedDF['Chorus_nostop'].apply(lambda x: lematizing(x))
modifiedDF['Chorus_lematized'] = modifiedDF['Chorus_tokenized'].apply(lambda x: lematizing(x))

modifiedDF.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


Song_ID  ...                                   Chorus_lematized
0        1  ...  [diana, let, me, be, the, one, to, light, a, f...
1        2  ...  [don, t, forget, where, you, belong, home, don...
2        3  ...  [i, m, sorry, if, i, say, i, need, you, but, i...
3        4  ...  [i, don, t, care, what, people, say, when, we,...
4        5  ...  [better, than, word, more, than, a, feeling, c...

[5 rows x 11 columns]

#Vectorizing Data
Vectorizing is the process of encoding text as integers i.e. numeric form to create feature vectors so that machine learning algorithms can understand our data.


#Vectorizing Data: Bag-Of-Words

Bag of Words (BoW) or CountVectorizer describes the presence of words within the text data. It gives a result of 1 if present in the sentence and 0 if not present. It, therefore, creates a bag of words with a document-matrix count in each text document.

Print corpus

In [ ]:
print(corpus)

['diana let one light fire insid eye lone even know feel cri diana let one lift heart save life think even realiz babi save mine', 'forget belong home forget belong home ever feel alon never proof song', 'sorri say need care not scare love caus not weaker wrong wrong make strong', 'care peopl say togeth know wanna one hold sleep want forev know wanna leav c mon babi happili', 'better word feel crazi love danc ceil everi time touch shook make wanna deep love god know babi', 'tell hurt vain see heart love rememb laugh let laugh burn even scream shout come back back oh carri fire water love hold closer hope heart strong enough night come find way dark', 'know know know know everi everi everi time lone sometim wanna cave wanna fight tri tri tri tri tri hold lone momma sorri not sober anymor daddi pleas forgiv drink spill floor one never left road sorri not sober anymor not sober anymor sorri promis get help intent sorri', 'walk th park saw anoth arm month apart look happier saw walk insid 

Creating the bag of words modal

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500)
X = cv.fit_transform(corpus).toarray()
y = modifiedDF.iloc[0:34, -1].values

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y

array(['Inspiration', 'Inspiration', 'Inspiration', 'Sad', 'Love',
       'Inspiration', 'Sad', 'Sad', 'Sad', 'Happy', 'Love', 'Inspiration',
       'Love', 'Inspiration', 'Inspiration', 'Angry', 'Inspiration',
       'Angry', 'Sad', 'Love', 'Sad', 'Inspiration', 'Sad', 'Sad', 'Love',
       'Sad', 'Love', 'Sad', 'Calm', 'Tense', 'Love', 'Inspiration',
       'Love', 'Love'], dtype=object)

Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Training the Kernal SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Love' 'Inspiration']
 ['Sad' 'Sad']
 ['Sad' 'Sad']
 ['Sad' 'Angry']
 ['Sad' 'Inspiration']
 ['Love' 'Love']
 ['Sad' 'Inspiration']]


Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 1]
 [0 0 1 2]
 [0 0 1 0]
 [0 0 0 2]]


0.42857142857142855

Appyling K-fold cross validation

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 29.63 %
Standard Deviation: 5.24 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  UserWarning,


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 10.67 %
Standard Deviation: 8.79 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 8)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 33.33 %
Standard Deviation: 18.16 %


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=8.
  UserWarning,


## Applying Grid Search to find the best model and the best parameters

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 2,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  UserWarning,


Best Accuracy: 51.65 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 3,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  UserWarning,


Best Accuracy: 40.74 %
Best Parameters: {'C': 0.25, 'gamma': 0.9, 'kernel': 'rbf'}


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 4,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=4.
  UserWarning,


Best Accuracy: 40.48 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


Best Accuracy: 36.67 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 6,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=6.
  UserWarning,


Best Accuracy: 36.67 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 7,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=7.
  UserWarning,


Best Accuracy: 33.33 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 8,
                           n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=8.
  UserWarning,


Best Accuracy: 41.67 %
Best Parameters: {'C': 0.25, 'kernel': 'linear'}
