<a href="https://colab.research.google.com/github/supuni9622/Test-Google-Colab/blob/main/Lyrics_Classification_NB_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pwd

'/content'

In [3]:
cd /content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2

/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2


In [4]:
pwd

'/content/drive/MyDrive/4th Year Research/M3/Test Implementation/Test-Google-Colab/TestV2'

In [5]:
dataset = pd.read_csv('Lyrical_data_3.csv',encoding='cp1252')

In [6]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [7]:
lyrics = dataset['Chorus']
lyrics

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
795                                                  NaN
796                                                  NaN
797                                                  NaN
798                                                  NaN
799                                                  NaN
Name: Chorus, Length: 800, dtype: object

In [8]:
dataset.dropna(how='all', axis=1, inplace=True)

In [9]:
dataset.head()

Song_ID  ...      Emotion
0        1  ...  Inspiration
1        2  ...  Inspiration
2        3  ...  Inspiration
3        4  ...          Sad
4        5  ...         Love

[5 rows x 4 columns]

In [10]:
dataset

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
795      796  ...          NaN
796      797  ...          NaN
797      798  ...          NaN
798      799  ...          NaN
799      800  ...          NaN

[800 rows x 4 columns]

In [11]:
lyrics2 = dataset['Chorus']
lyrics2

0      Diana,\rLet me be the one to light a fire insi...
1      Don't forget where you belong\rHome\rDon't for...
2      I'm sorry if I say, "I need you"\nBut I don't ...
3      I don't care what people say when we're togeth...
4      Better than words\rMore than a feeling Crazy i...
                             ...                        
795                                                  NaN
796                                                  NaN
797                                                  NaN
798                                                  NaN
799                                                  NaN
Name: Chorus, Length: 800, dtype: object

Checking the empty rows in dataset

In [12]:
print (dataset.isnull().sum())

Song_ID         0
Song_Title      0
Chorus        290
Emotion       290
dtype: int64


In [13]:
modifiedDF = dataset.dropna()
modifiedDF

Song_ID  ...      Emotion
0          1  ...  Inspiration
1          2  ...  Inspiration
2          3  ...  Inspiration
3          4  ...          Sad
4          5  ...         Love
..       ...  ...          ...
505      506  ...         Love
506      507  ...        Happy
507      508  ...        Happy
508      509  ...  Inspiration
509      510  ...        Happy

[510 rows x 4 columns]

In [27]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 509):
  Lyrics = re.sub('[^a-zA-Z]', ' ', modifiedDF['Chorus'][i])
  Lyrics = Lyrics.lower()
  Lyrics = Lyrics.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove('down')
  all_stopwords.remove('over')
  all_stopwords.remove('under')
  all_stopwords.remove('no')
  all_stopwords.remove('only')
  all_stopwords.remove("don't")
  all_stopwords.remove("aren't")
  Lyrics = [ps.stem(word) for word in Lyrics if not word in set(all_stopwords)]
  Lyrics = ' '.join(Lyrics)
  corpus.append(Lyrics)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Print corpus

In [15]:
print(corpus)

['diana let one light fire insid eye lone even know feel cri diana let one lift heart save life think even realiz babi save mine', 'forget belong home forget belong home ever feel alon never proof song', 'sorri say need care not scare love caus not weaker wrong wrong make strong', 'care peopl say togeth know wanna one hold sleep want forev know wanna leav c mon babi happili', 'better word feel crazi love danc ceil everi time touch shook make wanna deep love god know babi', 'tell hurt vain see heart love rememb laugh let laugh burn even scream shout come back back oh carri fire water love hold closer hope heart strong enough night come find way dark', 'know know know know everi everi everi time lone sometim wanna cave wanna fight tri tri tri tri tri hold lone momma sorri not sober anymor daddi pleas forgiv drink spill floor one never left road sorri not sober anymor not sober anymor sorri promis get help intent sorri', 'walk th park saw anoth arm month apart look happier saw walk insid 

Creating the bag of words modal

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = modifiedDF.iloc[0:509, -1].values

In [17]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
y

array(['Inspiration', 'Inspiration', 'Inspiration', 'Sad', 'Love',
       'Inspiration', 'Sad', 'Sad', 'Sad', 'Happy', 'Love', 'Inspiration',
       'Love', 'Inspiration', 'Inspiration', 'Angry', 'Inspiration',
       'Angry', 'Sad', 'Love', 'Sad', 'Inspiration', 'Sad', 'Sad', 'Love',
       'Sad', 'Love', 'Sad', 'Calm', 'Angry', 'Love', 'Inspiration',
       'Love', 'Love', 'Calm', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad',
       'Happy', 'Happy', 'Love', 'Inspiration', 'Love', 'Sad', 'Sad',
       'Inspiration', 'Love', 'Inspiration', 'Love', 'Inspiration',
       'Love', 'Inspiration', 'Inspiration', 'Love', 'Calm', 'Angry',
       'Inspiration', 'Angry', 'Angry', 'Angry', 'Love', 'Inspiration',
       'Sad', 'Sad', 'Inspiration', 'Inspiration', 'Happy', 'Angry',
       'Inspiration', 'Sad', 'Inspiration', 'Sad', 'Inspiration', 'Sad',
       'Sad', 'Calm', 'Inspiration', 'Love', 'Love', 'Sad', 'Inspiration',
       'Inspiration', 'Inspiration', 'Love', 'Inspiration', 'Inspiration',


Splitting the dataset into the Training set and Test set

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 20)

Training the Naive Bayes model on the Training set

In [101]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

Predicting the Test set results

In [102]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Inspiration' 'Happy']
 ['Inspiration' 'Inspiration']
 ['Sad' 'Sad']
 ['Love' 'Love']
 ['Inspiration' 'Inspiration']
 ['Inspiration' 'Inspiration']
 ['Love' 'Happy']
 ['Love' 'Love']
 ['Sad' 'Sad']
 ['Inspiration' 'Sad']
 ['Inspiration' 'Angry']
 ['Sad' 'Love']
 ['Happy' 'Inspiration']
 ['Inspiration' 'Sad']
 ['Sad' 'Sad']
 ['Sad' 'Inspiration']
 ['Happy' 'Love']
 ['Calm' 'Happy']
 ['Love' 'Love']
 ['Inspiration' 'Inspiration']
 ['Happy' 'Happy']
 ['Inspiration' 'Inspiration']
 ['Happy' 'Happy']
 ['Happy' 'Love']
 ['Happy' 'Happy']
 ['Sad' 'Angry']
 ['Happy' 'Angry']
 ['Love' 'Happy']
 ['Sad' 'Sad']
 ['Angry' 'Sad']
 ['Inspiration' 'Love']
 ['Sad' 'Sad']
 ['Sad' 'Sad']
 ['Love' 'Love']
 ['Love' 'Inspiration']
 ['Calm' 'Calm']
 ['Sad' 'Angry']
 ['Sad' 'Sad']
 ['Inspiration' 'Inspiration']
 ['Inspiration' 'Happy']
 ['Inspiration' 'Love']
 ['Inspiration' 'Inspiration']
 ['Angry' 'Inspiration']
 ['Inspiration' 'Sad']
 ['Sad' 'Inspiration']
 ['Angry' 'Inspiration']
 ['Sad' 'Inspiration']


Making the Confusion Matrix

In [103]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 3  0  1  1  1  2]
 [ 0  2  0  3  2  0]
 [ 1  3  5  4  3  3]
 [ 3  0  3 11  3  5]
 [ 0  0  3  2  9  3]
 [ 3  1  0  8  4 10]]


0.39215686274509803

Appyling K-fold cross validation

In [67]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 38.08 %
Standard Deviation: 5.75 %


In [68]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 5)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 35.35 %
Standard Deviation: 5.38 %


In [69]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 4)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 37.83 %
Standard Deviation: 6.03 %


In [70]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 8)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 36.86 %
Standard Deviation: 7.55 %


In [71]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 38.32 %
Standard Deviation: 7.15 %
